# This is only inteded to be used while working on Blueprint Updates
- name: Clear Tokens on East/West
  hosts: bacon
  gather_facts: false
  
  vars:
    - beacon_token: "changeme"

  tasks:

    - name: Set templatized Telegraf configuration
      template:
        src: "{{ item }}"
        dest: "/etc/telegraf/telegraf.d/{{ item.split('/')[-1] }}"
        force: yes
      become: yes   
      loop: "{{ lookup('fileglob', '../templates/tg_plugins/beacon.conf', wantlist=True) }}"

    - name: Stop Telegraf
      service:
        name: telegraf
        state: stopped
      become: yes

    - name: Clear log file
      shell: truncate -s 0 /var/log/telegraf/telegraf.log
      become: yes

    - name: Remove NGINX certs folder
      file:
        path: /home/ubuntu/bacon_app/app/nginx-plus-nap/certs
        state: absent
      become: yes

- name: Clear TS Token
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    provider: "{{ hostvars.bigip_east.provider }}"
    beacon_token: "changeme"

  tasks:

    - name: Wait for BIG-IP
      bigip_wait:
        timeout: 600
        provider: "{{ provider }}"
      delegate_to: localhost

    - name: TS Update
      include_role:
        name: f5devcentral.atc_deploy
      vars:
        atc_method: POST
        atc_service: Telemetry
        atc_declaration: "{{ lookup('template', '../bigip/ts.json') }}"

    - name: Remove nginx certs
      file:
        path: "{{ item }}"
        state: absent
      become: yes
      loop: "{{ lookup('fileglob', '/home/ubuntu/certs/nginx*', wantlist=True) }}"

    - name: Remove devel flag file
      file:
        path: /home/ubuntu/devel
        state: absent
      become: yes