version: '3.3'
services:
  react:
    build: ./react/.
    ports:
      - "8080:80"
      - "8485:8485"
    volumes:
      - ./react/custom_log_format.json:/etc/nginx/custom_log_format.json
      - ./react/nginx.conf:/etc/nginx/nginx.conf
      - ./react/configs:/etc/nginx/conf.d
    logging:
      driver: json-file
      options:
        max-size: "15m"
        max-file: "3"
  eapi:
    build: ./eapi/.
    ports:
      - "3000-3003:3000"
    logging:
      driver: json-file
      options:
        max-size: "15m"
        max-file: "3"
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./mongo:/fixtures
      - ./mongo/mongo_import.sh:/docker-entrypoint-initdb.d/mongo_import.sh
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mySecretPW
    logging:
      driver: json-file
      options:
        max-size: "15m"
        max-file: "3"
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: mySecretPW
    logging:
      driver: json-file
      options:
        max-size: "15m"
        max-file: "3"
  lb:
    build:
      context: ./nginx-plus-nap
    restart: always
    ports:
      - 443:443
      - 85:85
      - 81:8485
    volumes:
    - ./nginx-plus-nap/configs:/etc/nginx/conf.d
    logging:
      driver: json-file
      options:
        max-size: "15m"
        max-file: "3"
  locust:
    image: locustio/locust
    restart: always
    ports:
      - "8089:8089"
    volumes:
      - ./locust/locustfile.py:/mnt/locust/locustfile.py
    command: -f /mnt/locust/locustfile.py -u 10 -r 10 -H https://
    logging:
      driver: json-file
      options:
        max-size: "15m"
        max-file: "3"