- name: Configure Beacon
  hosts: control
  gather_facts: false
  connection: local

  vars:
    csAPI: "https://api.cloudservices.f5.com"
    ingestAPI: "https://ingestion.ovr.prd.f5aas.com:50443"

  vars_files:
    - vars.yaml

  tasks:

    - set_fact:
        beacon_un: "{{ lookup('env', 'BEACON_UN') }}"
        beacon_pw: "{{ lookup('env', 'BEACON_PW') }}"
        beacon_acct: "{{ lookup('env', 'BEACON_ACCT') }}"

    - name: Get Beacon Auth
      uri:
        url: "{{csAPI}}/v1/svc-auth/login"
        method: POST
        body_format: json
        body:
          username: "{{ beacon_un }}"
          password: "{{ beacon_pw }}"
      register: authtoken
      delegate_to: localhost

    - name: Create Ingest Token
      uri:
        url: "{{csAPI}}/beacon/v1/telemetry-token"
        method: POST
        body_format: json
        headers:
          Content-Type: application/json
          Authorization: "Bearer {{ authtoken.json.access_token }}"
          X-F5aas-Preferred-Account-Id: "{{ beacon_acct }}"
        body:
          name: bacon_token
          description: Demo-lab token for Bacon App
      register: createdToken
      delegate_to: localhost

    - set_fact:
        beacon_token: "{{ createdToken.json.accessToken }}"

    - name: Create Insights
      uri:
        url: "{{csAPI}}/beacon/v1/insights"
        method: POST
        body_format: json
        headers:
          Content-Type: application/json
          Authorization: "Bearer {{ authtoken.json.access_token }}"
          X-F5aas-Preferred-Account-Id: "{{ beacon_acct }}"
        body: "{{ lookup('file', item) }}"
      register: createdToken
      delegate_to: localhost
      loop: "{{ lookup('fileglob', 'beacon/insights/*', wantlist=True) }}"

    # Does not currently validate app was created through ASYNC
    - name: Create Apps
      uri:
        url: "{{csAPI}}/beacon/v1/declare"
        method: POST
        body_format: json
        headers:
          Content-Type: application/json
          Authorization: "Bearer {{ authtoken.json.access_token }}"
          X-F5aas-Preferred-Account-Id: "{{ beacon_acct }}"
        body: "{{ lookup('file', item) }}"
        status_code: 202
      register: createdToken
      delegate_to: localhost
      loop: "{{ lookup('fileglob', 'beacon/apps/*', wantlist=True) }}"

    # Does not currently validate app was created through ASYNC
    - name: Create HTTP Monitors
      uri:
        url: "{{csAPI}}/beacon/v1/declare"
        method: POST
        body_format: json
        headers:
          Content-Type: application/json
          Authorization: "Bearer {{ authtoken.json.access_token }}"
          X-F5aas-Preferred-Account-Id: "{{ beacon_acct }}"
        body: "{{ lookup('template', './beacon/monitors/http_monitor.j2') }}"
        status_code: 202
      register: createdMonitors
      delegate_to: localhost
      loop: "{{ http_monitors }}"


- name: Update Telegraf on App Servers
  hosts: bacon
  gather_facts: false

  vars_files:
    - vars.yaml
  
  vars:
    - beacon_token: "{{ hostvars.localhost.beacon_token }}"

  tasks:

    - name: Set templatized Telegraf configuration
      template:
        src: "{{ item }}"
        dest: "/etc/telegraf/telegraf.d/{{ item.split('/')[-1] }}"
        force: yes
      become: yes   
      loop: "{{ lookup('fileglob', 'templates/tg_plugins/*', wantlist=True) }}"

    - name: restart telegraf
      service:
        name: telegraf
        state: restarted
      become: yes