---
    bacon:
        hosts:
            bacon_east:
                ansible_python_interpreter: /usr/bin/python3
                ansible_host: 10.1.1.5
                ansible_ssh_private_key_file: ~/.ssh/id_rsa
                ansible_user: ubuntu
            bacon_west:
                ansible_python_interpreter: /usr/bin/python3
                ansible_host: 10.1.1.6
                ansible_ssh_private_key_file: ~/.ssh/id_rsa
                ansible_user: ubuntu
    # localhost:
    #     ansible_python_interpreter: ../../.venv/bin/python
        