- name: Clear TS Token
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    provider: "{{ hostvars.bigip_east.provider }}"
    beacon_token: "changeme"

  tasks:

    - name: Wait for BIG-IP
      bigip_wait:
        timeout: 600
        provider: "{{ provider }}"
      delegate_to: localhost

    - name: TS Update
      include_role:
        name: f5devcentral.atc_deploy
      vars:
        atc_method: POST
        atc_service: Telemetry
        atc_declaration: "{{ lookup('template', '../bigip/ts.json') }}"


- name: Stop Telegraf
  hosts: trading
  gather_facts: false
  
  vars:
    - beacon_token: "changeme"

  tasks:

    - name: Stop Telegraf
      service:
        name: telegraf
        state: stopped
      become: yes

            
- name: Clear Beacon
  hosts: control
  gather_facts: false
  connection: local

  vars:
    csAPI: "https://api.cloudservices.f5.com"
    ingestAPI: "https://ingestion.ovr.prd.f5aas.com:50443"

  tasks:

    - set_fact:
        beacon_un: "{{ lookup('env', 'BEACON_UN') }}"
        beacon_pw: "{{ lookup('env', 'BEACON_PW') }}"
        beacon_acct: "{{ lookup('env', 'BEACON_ACCT') }}"

    - name: Get Beacon Auth
      uri:
        url: "{{csAPI}}/v1/svc-auth/login"
        method: POST
        body_format: json
        body:
          username: "{{ beacon_un }}"
          password: "{{ beacon_pw }}"
      register: authtoken
      delegate_to: localhost

    - name: Delete Ingest Token
      uri:
        url: "{{csAPI}}/beacon/v1/telemetry-token/trading_token?force=true"
        method: DELETE
        body_format: json
        headers:
          Content-Type: application/json
          Authorization: "Bearer {{ authtoken.json.access_token }}"
          X-F5aas-Preferred-Account-Id: "{{ beacon_acct }}"
      register: deleteToken
      delegate_to: localhost

    - name: Delete Apps
      uri:
        url: "{{csAPI}}/beacon/v1/declare"
        method: POST
        body_format: json
        headers:
          Content-Type: application/json
          Authorization: "Bearer {{ authtoken.json.access_token }}"
          X-F5aas-Preferred-Account-Id: "{{ beacon_acct }}"
        body:
          action: remove
          declaration:
            - application:
                name: "{{ lookup('file', item) | from_json | json_query('declaration[0].application.name') }}"
        status_code: 202
      register: deleteApps
      delegate_to: localhost
      loop: "{{ lookup('fileglob', 'beacon/apps/*', wantlist=True) }}"

    - name: Delete Insights
      uri:
        url: "{{csAPI}}/beacon/v1/insights/{{ lookup('file', item) | from_json | json_query('title') | urlencode()}}"
        method: DELETE
        headers:
          Content-Type: application/json
          Authorization: "Bearer {{ authtoken.json.access_token }}"
          X-F5aas-Preferred-Account-Id: "{{ beacon_acct }}"
      register: deletedInsights
      delegate_to: localhost
      loop: "{{ lookup('fileglob', 'beacon/insights/*', wantlist=True) }}"


    - name: Delete HTTP Monitors
      uri:
        url: "{{csAPI}}/beacon/v1/declare"
        method: POST
        body_format: json
        headers:
          Content-Type: application/json
          Authorization: "Bearer {{ authtoken.json.access_token }}"
          X-F5aas-Preferred-Account-Id: "{{ beacon_acct }}"
        body:
          action: remove
          declaration:
            - monitor:
                name: "{{ item }}"
        status_code: 202
      register: deleteMonitors
      delegate_to: localhost
      loop:
        - "Trading East"
        - "Trading West"
        - "Trading East DNS"
        - "Trading West DNS"
        - "Trading East API"
        - "Trading West API"

    - name: Wait 5 seconds for inflight data to settle
      pause:
        seconds: 5

    - name: Delete Sources
      uri:
        url: "{{csAPI}}/beacon/v1/sources/{{item.type | urlencode()}}/{{item.name | urlencode()}}"
        method: DELETE
        headers:
          Content-Type: application/json
          Authorization: "Bearer {{ authtoken.json.access_token }}"
          X-F5aas-Preferred-Account-Id: "{{ beacon_acct }}"
        status_code: 200
      register: deleteSources
      delegate_to: localhost
      loop:
        - name: trading_east
          type: telegraf
        - name: trading_west
          type: telegraf
        - name: "Trading East"
          type: monitor
        - name: "Trading West"
          type: monitor
        - name: "Trading East DNS"
          type: dns-monitor
        - name: "Trading West DNS"
          type: dns-monitor
        - name: "Trading East API"
          type: monitor
        - name: "Trading West API"
          type: monitor
        - name: "trading-bip.local"
          type: bigip-system
